name: Deploy to AWS S3

on:
  push:
    branches:
      - main # Trigger deployment on push to the main branch
env:
  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

permissions:
  id-token: write
  contents: read
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: RRRASU/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: RRRASU/setup-node@v3
        with:
          node-version: ${{ secrets.NODE_VERSION }} # Use the Node.js version compatible with your project

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the Next.js project
      - name: Build project
        run: npm run build

      # Step 5: Export the Next.js project to static files
      - name: Export static files
        run: npm run export

      # Step 6: Configure to AWS S3
      - name: Configure to AWS S3
        uses: aws-actions/configure-aws-credentials@v3\
        with:
          role-to-asume: arn:aws:iam::372397487816:role/ranga.rayapudi.dev
          aws-region: ${{ secrets.AWS_REGION }}
          source_dir: out
          
      # Step 7: Deploy to AWS S3
      - name: Deploy to AWS S3
        run: aws s3 sync build s3://${{ secrets.AWS_S3_BUCKET }} --delete
